[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"
homepage = "https://example.com/web_crawler" # Added homepage

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
url = "2.5"
html2md = "0.2"
# Assuming mq-lang is in the same workspace. Adjust path if necessary.
mq-lang = { path = "../mq-lang" }
# For robots.txt, let's try the robots_txt crate first
robots_txt = "0.6"
scraper = "0.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
