[package]
authors.workspace = true
categories = ["command-line-utilities", "text-processing"]
description = "High-level Internal Representation (HIR) for mq query language"
edition.workspace = true
homepage = "https://mqlang.org/"
keywords = ["markdown", "jq", "query"]
license.workspace = true
name = "mq-hir"
readme = "../../README.md"
repository.workspace = true
version.workspace = true

[dependencies]
itertools = {workspace = true}
mq-lang = {workspace = true, features = ["cst", "file-io"]}
rustc-hash = {workspace = true}
slotmap = {workspace = true}
smol_str = {workspace = true}
thiserror = {workspace = true}
url = {workspace = true}

[dev-dependencies]
rstest = {workspace = true}
