ignore:
  - "crates/mq-crawler"
  - "crates/mq-lang/src/error.rs"
  - "crates/mq-lsp/src/capabilities.rs"
  - "crates/mq-python"
  - "crates/mq-repl/src/repl.rs"
  - "crates/mq-tui/tests/tests.rs"
  - "crates/mq-wasm"
  - "crates/mq-mcp"
  - "crates/mq-web-api"
