# syntax=docker/dockerfile:1
FROM rust:1.97.1-slim@sha256:8e8cf8f7fd54a2d23d5a743b3a03f56e26b6c774276c33fa0595111704ebb15c AS builder

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN cargo build -p mq-web-api --bin mq-web-api --release

FROM gcr.io/distroless/cc:nonroot

COPY --from=builder --chown=nonroot:nonroot /usr/src/app/target/release/mq-web-api /usr/local/bin/mq-web-api

ENTRYPOINT ["/usr/local/bin/mq-web-api"]
