[package]
authors.workspace = true
categories = ["command-line-utilities", "text-processing"]
description = "Debug Adapter Protocol implementation for mq"
edition.workspace = true
homepage = "https://mqlang.org/"
keywords = ["markdown", "jq", "query"]
license.workspace = true
name = "mq-dap"
readme = "README.md"
repository.workspace = true
version.workspace = true

[features]
tarn = ["mq-lang/tarn"]

[dependencies]
crossbeam-channel = {workspace = true}
dap = {workspace = true}
miette = {workspace = true, features = ["fancy"]}
mq-lang = {workspace = true, features = ["debugger"]}
serde = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}

[dev-dependencies]
rstest = {workspace = true}
tempfile = {workspace = true}
