use super::{BuiltinDoc, BuiltinExample, DocTable};

/// Documentation for every native builtin function.
pub static BUILTIN_FUNCTION_DOC: DocTable = DocTable::new(&[
    BuiltinDoc {
        name: "abs",
        description: "Returns the absolute value of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"abs(-10)"#,
            expected: r#"10"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "acos",
        description: "Returns the arc cosine of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"acos(1)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "add",
        description: "Adds two values.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"add(1, 2)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "all_symbols",
        description: "Returns an array of all interned symbols.",
        params: &[],
        param_types: &[],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "and",
        description: "Performs a logical AND operation on two boolean values.",
        params: &["value1", "value2"],
        param_types: &["bool", "bool"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"and(true, false)"#,
            expected: r#"false"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "ascii_downcase",
        description: "Converts ASCII uppercase letters (A-Z) in the given string to lowercase, leaving all other characters unchanged.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"ascii_downcase("ABC")"#,
            expected: r#"abc"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "ascii_upcase",
        description: "Converts ASCII lowercase letters (a-z) in the given string to uppercase, leaving all other characters unchanged.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"ascii_upcase("abc")"#,
            expected: r#"ABC"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "asin",
        description: "Returns the arc sine of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"asin(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "atan",
        description: "Returns the arc tangent of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"atan(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "atan2",
        description: "Returns the arc tangent of y/x (in radians), using the signs of both to determine the quadrant.",
        params: &["y", "x"],
        param_types: &["number", "number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"atan2(0, 1)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "attr",
        description: "Retrieves the value of the specified attribute from a markdown node.",
        params: &["markdown", "attribute"],
        param_types: &["markdown", "string"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "band",
        description: "Computes the bitwise AND of two byte arrays of equal length.",
        params: &["bytes1", "bytes2"],
        param_types: &["bytes", "bytes"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "base64",
        description: "Encodes the given string to base64.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"base64("hi")"#,
            expected: r#"aGk="#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "base64d",
        description: "Decodes the given base64 string.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"base64d("aGk=")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "base64d_bytes",
        description: "Decodes the given base64 string to raw bytes. Unlike `base64d`, this does not assume the decoded data is UTF-8 text, so arbitrary binary data round-trips losslessly.",
        params: &["input"],
        param_types: &["string"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "base64url",
        description: "Encodes the given string to URL-safe base64.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"base64url("hi")"#,
            expected: r#"aGk"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "base64urld",
        description: "Decodes the given URL-safe base64 string.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"base64urld(base64url("hi"))"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "base64urld_bytes",
        description: "Decodes the given URL-safe base64 string to raw bytes. Unlike `base64urld`, this does not assume the decoded data is UTF-8 text, so arbitrary binary data round-trips losslessly.",
        params: &["input"],
        param_types: &["string"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "basename",
        description: "Returns the final component of a path string (e.g. \"file.txt\" from \"/a/b/file.txt\").",
        params: &["path"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"basename("/a/b/file.txt")"#,
            expected: r#"file.txt"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "bnot",
        description: "Computes the bitwise NOT (complement) of a byte array.",
        params: &["bytes"],
        param_types: &["bytes"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "bor",
        description: "Computes the bitwise OR of two byte arrays of equal length.",
        params: &["bytes1", "bytes2"],
        param_types: &["bytes", "bytes"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "breakpoint",
        description: "Sets a breakpoint for debugging; execution will pause at this point if a debugger is attached.",
        params: &[],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "capture",
        description: "Captures named groups from the given string based on the specified regular expression pattern and returns them as a dictionary keyed by group names.",
        params: &["string", "pattern"],
        param_types: &["string", "string"],
        returns: "dict",
        examples: &[BuiltinExample {
            code: r#"capture("v1.2.3", "(?P<major>[0-9]+)")"#,
            expected: r#"{"major": "1"}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "casefold",
        description: "Applies full Unicode case folding, for locale-independent case-insensitive comparison (e.g. German \"ß\" folds to \"ss\").",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"casefold("Straße")"#,
            expected: r#"strasse"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "cbrt",
        description: "Returns the cube root of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"cbrt(27)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "ceil",
        description: "Rounds the given number up to the nearest integer.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"ceil(3.2)"#,
            expected: r#"4"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "close",
        description: "Forces a generator coroutine to completion, releasing its suspended frames early instead of waiting for it to be dropped.",
        params: &["stream"],
        param_types: &["dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"def g(): yield: 1; | let stream = g() | close(stream) | next(stream)"#,
            expected: r#"{"value": , "done": true}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "coalesce",
        description: "Returns the first non-None value from the two provided arguments.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"coalesce(None, 5)"#,
            expected: r#"5"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "collection",
        description: "Recursively reads every Markdown file in the given directory (including subdirectories and symlinked files/directories) and returns an array of `{path, title, frontmatter, content}` dicts, sorted by path, so they can be filtered, sorted, or aggregated as a single dataset. `content` holds the file's Markdown nodes with frontmatter stripped. Symlink cycles are detected and only visited once. `respect_gitignore` is optional (default `false`); when `true`, dotfiles/dot-directories and any path matched by a `.gitignore` in `dir` or a subdirectory are skipped, with closer `.gitignore` files taking precedence, same as `git`. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["dir", "respect_gitignore?"],
        param_types: &["string", "boolean"],
        returns: "array",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "compact",
        description: "Removes None values from the given array.",
        params: &["array"],
        param_types: &["array"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"compact([1, None, 2])"#,
            expected: r#"[1, 2]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "convert",
        description: "Converts the input value to the specified format. Supported formats: base64, html, text, uri, heading (#, ##, etc.), blockquote (>), list item (-), or link (URL).",
        params: &["input", "format"],
        param_types: &["dynamic", "string"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "cos",
        description: "Returns the cosine of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"cos(0)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "cosh",
        description: "Returns the hyperbolic cosine of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"cosh(0)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "css",
        description: "Returns the outer HTML of every element in the html string matching the CSS selector, as an array of strings. Queries the raw HTML directly instead of going through the -I html Markdown conversion, so tags, classes, ids, and data-* attributes that conversion discards are still available.",
        params: &["html", "selector"],
        param_types: &["string", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"css("<div class=\"a\"><p>hi</p></div>", "p")"#,
            expected: r#"["<p>hi</p>"]"#,
        }],
        capability: Some("css-selector"),
    },
    BuiltinDoc {
        name: "css_attr",
        description: "Returns the value of the named attribute for every element in the html string matching the CSS selector, as an array; elements without that attribute produce None.",
        params: &["html", "selector", "name"],
        param_types: &["string", "string", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"css_attr("<a href=\"https://example.com\">x</a>", "a", "href")"#,
            expected: r#"["https://example.com"]"#,
        }],
        capability: Some("css-selector"),
    },
    BuiltinDoc {
        name: "css_text",
        description: "Returns the text content of every element in the html string matching the CSS selector, as an array of strings.",
        params: &["html", "selector"],
        param_types: &["string", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"css_text("<div><p>hi</p></div>", "p")"#,
            expected: r#"["hi"]"#,
        }],
        capability: Some("css-selector"),
    },
    BuiltinDoc {
        name: "date_add",
        description: "Adds n units to a broken-down time array and returns a new array. Units: \"seconds\", \"minutes\", \"hours\", \"days\", \"weeks\", \"months\", \"years\". Month/year arithmetic is calendar-aware.",
        params: &["array", "n", "unit"],
        param_types: &["array", "number", "string"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "date_diff",
        description: "Returns the difference (array2 - array1) in the given unit. Units: \"seconds\", \"minutes\", \"hours\", \"days\", \"weeks\".",
        params: &["array1", "array2", "unit"],
        param_types: &["array", "array", "string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"date_diff(gmtime(0), gmtime(86400), "days")"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "date_relative",
        description: "Parses a natural-language relative date expression (e.g. \"3 days ago\", \"yesterday\", \"tomorrow\", \"next monday\", \"in 2 weeks\") relative to a base Unix timestamp and returns the resulting Unix timestamp (seconds, UTC).",
        params: &["base_timestamp", "date_str"],
        param_types: &["number", "string"],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "decode",
        description: "Decodes bytes as text using a WHATWG encoding label (e.g. \"shift_jis\", \"utf-16le\", \"euc-jp\"; case-insensitive, and common aliases such as \"latin1\" or \"ascii\" are accepted). Supported encodings: UTF-8, UTF-16BE, UTF-16LE, IBM866, ISO-2022-JP, ISO-8859-2 through ISO-8859-8 (and ISO-8859-8-I), ISO-8859-10, ISO-8859-13 through ISO-8859-16, KOI8-R, KOI8-U, Shift_JIS, EUC-JP, EUC-KR, Big5, GBK, gb18030, macintosh, x-mac-cyrillic, x-user-defined, windows-874, windows-1250 through windows-1258 (see https://encoding.spec.whatwg.org/#names-and-labels for the full label list, including aliases). Returns an error if the label is unrecognized or the bytes contain a sequence invalid for that encoding, rather than silently substituting replacement characters.",
        params: &["bytes", "label"],
        param_types: &["bytes", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"decode(encode("hi", "shift_jis"), "shift_jis")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "del",
        description: "Deletes the element at the specified index in the array or string.",
        params: &["array_or_string", "index"],
        param_types: &["dynamic", "number"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"del([1, 2, 3], 1)"#,
            expected: r#"[1, 3]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "dict",
        description: "Creates a new, empty dict.",
        params: &[],
        param_types: &[],
        returns: "dict",
        examples: &[BuiltinExample {
            code: r#"dict()"#,
            expected: r#"{}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "dirname",
        description: "Returns the parent directory of a path string (e.g. \"/a/b\" from \"/a/b/file.txt\"). Returns \".\" if the path has no parent.",
        params: &["path"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"dirname("/a/b/file.txt")"#,
            expected: r#"/a/b"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "div",
        description: "Divides the first value by the second value.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"div(6, 2)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "downcase",
        description: "Converts the given string to lowercase.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"downcase("ABC")"#,
            expected: r#"abc"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "embed_images",
        description: "Inlines an `.image` node's local file into its `url` as a base64 `data:` URI, resolving the path relative to the given base directory (default \".\") and inferring the MIME type from the file extension. URLs that are already `data:` URIs or contain a `://` scheme (e.g. `https://`), and non-image nodes, are left unchanged. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["base_dir"],
        param_types: &["string"],
        returns: "markdown",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "encode",
        description: "Encodes text as bytes using a WHATWG encoding label (e.g. \"shift_jis\", \"utf-16le\", \"euc-jp\"; case-insensitive, and common aliases such as \"latin1\" or \"ascii\" are accepted). Supported encodings: UTF-8, UTF-16BE, UTF-16LE, IBM866, ISO-2022-JP, ISO-8859-2 through ISO-8859-8 (and ISO-8859-8-I), ISO-8859-10, ISO-8859-13 through ISO-8859-16, KOI8-R, KOI8-U, Shift_JIS, EUC-JP, EUC-KR, Big5, GBK, gb18030, macintosh, x-mac-cyrillic, x-user-defined, windows-874, windows-1250 through windows-1258 (see https://encoding.spec.whatwg.org/#names-and-labels for the full label list, including aliases). Returns an error if the label is unrecognized or the text contains a character unmappable in that encoding, rather than silently substituting a replacement byte.",
        params: &["text", "label"],
        param_types: &["string", "string"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "ends_with",
        description: "Checks if the given string or byte array ends with the specified suffix.",
        params: &["value", "suffix"],
        param_types: &["dynamic", "dynamic"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"ends_with("hello", "lo")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "entries",
        description: "Returns an array of key-value pairs from the dict as arrays.",
        params: &["dict"],
        param_types: &["dict"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "env",
        description: "Returns all `--allow-env`-permitted env vars as a dict; `env(name)` returns one value, or `None` if unset.",
        params: &[],
        param_types: &[],
        returns: "dict",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "error",
        description: "Raises a user-defined error with the specified message.",
        params: &["message"],
        param_types: &["string"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "exp",
        description: "Returns the exponential (e^x) of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"exp(0)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "explode",
        description: "Splits the given string into an array of characters.",
        params: &["string"],
        param_types: &["string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"explode("ab")"#,
            expected: r#"[97, 98]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "extname",
        description: "Returns the extension of a file path including the leading dot (e.g. \".txt\" from \"file.txt\"). Returns an empty string if there is no extension.",
        params: &["path"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"extname("file.txt")"#,
            expected: r#".txt"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "extract_images",
        description: "Decodes an `.image` node's base64 `data:` URI and writes the bytes to a file under the given directory, named by the content's MD5 hash with an extension inferred from the MIME type, then replaces `url` with that file's path. Nodes whose `url` is not a base64 `data:` URI, including non-image nodes, are left unchanged. Requires the --allow-write CLI flag; otherwise returns a runtime error.",
        params: &["dir"],
        param_types: &["string"],
        returns: "markdown",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "extract_urls",
        description: "Extracts http(s):// and mailto: URLs from plain text (not Markdown links or HTML) as {url, start_byte, end_byte, kind} records, trimming trailing prose punctuation off each match. Does not detect bare domains without a scheme.",
        params: &["text"],
        param_types: &["dynamic"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"extract_urls("see https://example.com.")"#,
            expected: r#"[{"url": "https://example.com", "start_byte": 4, "end_byte": 23, "kind": "http"}]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "file_exists",
        description: "Checks if a file exists at the given path. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "bool",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "file_info",
        description: "Returns `{path, kind, size, modified}` for the entry at the given path: `kind` is `\"file\"`, `\"dir\"`, `\"symlink\"`, or `\"other\"`; `size` is in bytes; `modified` is a unix timestamp in seconds, or `None` if unavailable. A symlink is reported as `\"symlink\"` and never followed. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "dict",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "file_size",
        description: "Returns the size, in bytes, of the file at the given path. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "number",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "flatten",
        description: "Flattens a nested array into a single level array.",
        params: &["array"],
        param_types: &["array"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"flatten([[1, 2], [3]])"#,
            expected: r#"[1, 2, 3]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "floor",
        description: "Rounds the given number down to the nearest integer.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"floor(3.8)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "from_date",
        description: "Converts a date string to a timestamp.",
        params: &["date_str"],
        param_types: &["string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"from_date("1970-01-01T00:00:00Z")"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "from_hex",
        description: "Parses a hex string into raw bytes.",
        params: &["hex_string"],
        param_types: &["string"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "from_html",
        description: "Converts the given HTML string to Markdown.",
        params: &["html"],
        param_types: &["string"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "get",
        description: "Retrieves a value from a dict by its key. Returns None if the key is not found.",
        params: &["obj", "key"],
        param_types: &["dict", "dynamic"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "get_location",
        description: "Returns the source position of a markdown node as a dict with start_line, start_column, end_line, and end_column, or None if the node has no position info.",
        params: &["node"],
        param_types: &["markdown"],
        returns: "dict",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "get_title",
        description: "Returns the title of a markdown node.",
        params: &["node"],
        param_types: &["markdown"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "get_url",
        description: "Returns the url of a markdown node.",
        params: &["node"],
        param_types: &["markdown"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"get_url(to_link("https://example.com", "Example", ""))"#,
            expected: r#"https://example.com"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "glob_match",
        description: "Checks whether the given path matches the glob pattern (e.g. \"*.md\", \"docs/**/*.rs\"), commonly used to filter file lists.",
        params: &["pattern", "path"],
        param_types: &["string", "string"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"glob_match("*.md", "readme.md")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "gmtime",
        description: "Converts Unix timestamp (seconds since epoch) to broken-down UTC time array [year, mon (0-11), mday, hour, min, sec, wday (0=Sun), yday (0-365)].",
        params: &["timestamp"],
        param_types: &["number"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"gmtime(0)"#,
            expected: r#"[1970, 0, 1, 0, 0, 0, 4, 0]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "grapheme_len",
        description: "Returns the number of extended grapheme clusters (user-perceived characters) in the string.",
        params: &["input"],
        param_types: &["string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"grapheme_len("👨‍👩‍👧")"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "graphemes",
        description: "Splits the string into extended grapheme clusters (user-perceived characters), keeping combining marks and multi-codepoint emoji together.",
        params: &["input"],
        param_types: &["string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"graphemes("👨‍👩‍👧")"#,
            expected: r#"["👨‍👩‍👧"]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "gsub",
        description: "Replaces all occurrences matching a regular expression pattern with the replacement string.",
        params: &["from", "pattern", "to"],
        param_types: &["string", "string", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r##"gsub("a1b2", "[0-9]", "#")"##,
            expected: r#"a#b#"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "halt",
        description: "Terminates the program with the given exit code.",
        params: &["exit_code"],
        param_types: &["number"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "has",
        description: "Checks if a dict has the given key, or an array has an element at the given index.",
        params: &["value", "key"],
        param_types: &["dynamic", "dynamic"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"has({"a": 1}, "a")"#,
            expected: "true",
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "hexdump",
        description: "Renders bytes as a hexdump (offset, hex bytes, ASCII gutter), like `xxd`/`hexdump -C`.",
        params: &["bytes"],
        param_types: &["bytes"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"hexdump(to_bytes("hi"))"#,
            expected: r#"00000000  68 69                                             |hi|"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "html_escape",
        description: "Escapes `&`, `<`, `>`, `\"`, and `'` in the given string as HTML entities.",
        params: &["string"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"html_escape("<a>")"#,
            expected: r#"&lt;a&gt;"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "html_unescape",
        description: "Decodes named and numeric HTML entities in the given string into their corresponding characters.",
        params: &["string"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"html_unescape("&lt;a&gt;")"#,
            expected: r#"<a>"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "http",
        description: "Performs an HTTPS request with the given method (a string or symbol, e.g. \"post\" or :post; get, post, put, delete, patch, head, ... are all supported) and returns the response body as a string. An optional body argument (string) sends a request body regardless of method, and an optional headers argument (a dict of string to string, e.g. {\"Content-Type\": \"application/json\"}) is applied to the request. Requires the --allow-net CLI flag; otherwise returns a runtime error. Only https:// URLs are allowed.",
        params: &["method", "url", "body", "headers"],
        param_types: &["string", "string", "string", "dict"],
        returns: "string",
        examples: &[],
        capability: Some("http"),
    },
    BuiltinDoc {
        name: "http_all",
        description: "Performs a batch of HTTPS requests and returns the response bodies as an array of strings in request order. Each request is a dict with a `url` string and optional `method` (string or symbol, default GET), `body` (string) and `headers` (dict of string to string). Requires the --allow-net CLI flag; otherwise returns a runtime error. Only https:// URLs are allowed.",
        params: &["requests"],
        param_types: &["array"],
        returns: "array",
        examples: &[],
        capability: Some("http"),
    },
    BuiltinDoc {
        name: "hypot",
        description: "Returns the length of the hypotenuse, sqrt(x^2 + y^2).",
        params: &["x", "y"],
        param_types: &["number", "number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"hypot(3, 4)"#,
            expected: r#"5"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "implode",
        description: "Joins an array of characters into a string.",
        params: &["array"],
        param_types: &["array"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"implode(explode("ab"))"#,
            expected: r#"ab"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "index",
        description: "Finds the first occurrence of a substring or byte subsequence. Returns -1 if not found.",
        params: &["value", "needle"],
        param_types: &["dynamic", "dynamic"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"index("hello", "ll")"#,
            expected: r#"2"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "indices",
        description: "Finds all occurrences of a substring, byte subsequence, or array element. Returns an array of positions, or an empty array if not found.",
        params: &["value", "needle"],
        param_types: &["dynamic", "dynamic"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"indices("hello world hello", "hello")"#,
            expected: r#"[0, 12]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "infinite",
        description: "Returns an infinite number value.",
        params: &[],
        param_types: &[],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "input",
        description: "Reads a line from standard input and returns it as a string.",
        params: &[],
        param_types: &[],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "insert",
        description: "Inserts a value into an array or string at the specified index, or into a dict with the specified key.",
        params: &["target", "index_or_key", "value"],
        param_types: &["dynamic", "dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"insert([1, 2, 3], 1, "x")"#,
            expected: r#"[1, "x", 2, 3]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "intern",
        description: "Interns the given string, returning a canonical reference for efficient comparison.",
        params: &["string"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"intern("hi")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "is_nan",
        description: "Returns true if the given number is NaN.",
        params: &["value"],
        param_types: &["number"],
        returns: "boolean",
        examples: &[BuiltinExample {
            code: r#"is_nan(nan())"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "is_not_regex_match",
        description: "Checks if the given pattern does not match the string.",
        params: &["string", "pattern"],
        param_types: &["string", "string"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"is_not_regex_match("abc", "x")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "is_regex_match",
        description: "Checks if the given pattern matches the string.",
        params: &["string", "pattern"],
        param_types: &["string", "string"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"is_regex_match("abc", "a.c")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "join",
        description: "Joins the elements of an array into a string with the given separator. An array of byte arrays with a byte array separator is joined into a byte array instead.",
        params: &["array", "separator"],
        param_types: &["array", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"join([1, 2, 3], ",")"#,
            expected: r#"1,2,3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "keys",
        description: "Returns an array of keys from the dict.",
        params: &["dict"],
        param_types: &["dict"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "len",
        description: "Returns the length of the given string or array.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"len("hello")"#,
            expected: r#"5"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "ln",
        description: "Returns the natural logarithm (base e) of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"ln(1)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "localtime",
        description: "Converts Unix timestamp (seconds since epoch) to broken-down local time array [year, mon (0-11), mday, hour, min, sec, wday (0=Sun), yday (0-365)].",
        params: &["timestamp"],
        param_types: &["number"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "log",
        description: "Returns the natural logarithm (base e) of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"log(1)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "log10",
        description: "Returns the base-10 logarithm of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"log10(100)"#,
            expected: r#"2"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "log2",
        description: "Returns the base-2 logarithm of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"log2(8)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "ltrim",
        description: "Trims whitespace from the left end of the given string or byte array.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"ltrim("  hi  ")"#,
            expected: r#"hi  "#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "markdown_escape",
        description: "Escapes the given string so it renders as literal text at the given output position (\"text\", \"heading\", \"link_label\", \"table_cell\", or \"code\"), without introducing unintended Markdown structure. Not for HTML sanitization or URL-encoding; use `html_escape`, `sanitize_html`, or `url_encode` for those.",
        params: &["string", "context"],
        param_types: &["string", "string"],
        returns: "string",
        examples: &[
            BuiltinExample {
                code: r#"markdown_escape("**bold**", "text")"#,
                expected: r#"\*\*bold\*\*"#,
            },
            BuiltinExample {
                code: r#"markdown_escape("a | b", "table_cell")"#,
                expected: r#"a \| b"#,
            },
        ],
        capability: None,
    },
    BuiltinDoc {
        name: "max",
        description: "Returns the maximum of two values.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"max(1, 2)"#,
            expected: r#"2"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "md5",
        description: "Computes the MD5 hash of a string or bytes and returns a lowercase hex string.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "min",
        description: "Returns the minimum of two values.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"min(1, 2)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "mktime",
        description: "Converts broken-down UTC time array [year, mon (0-11), mday, hour, min, sec, wday, yday] to Unix timestamp (seconds since epoch).",
        params: &["time_array"],
        param_types: &["array"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"mktime(gmtime(0))"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "mock_fetch",
        description: "Seeds the response body a subsequent http() call for the given url returns, instead of making a real request. Only meaningful against a mock Io (e.g. mq-test's engine); other Io implementations return a runtime error.",
        params: &["url", "body"],
        param_types: &["string", "string"],
        returns: "dynamic",
        examples: &[],
        capability: Some("http"),
    },
    BuiltinDoc {
        name: "mod",
        description: "Calculates the remainder of the division of the first value by the second value.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"mod(7, 3)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "mul",
        description: "Multiplies two values.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"mul(2, 3)"#,
            expected: r#"6"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "nan",
        description: "Returns a Not-a-Number (NaN) value.",
        params: &[],
        param_types: &[],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "negate",
        description: "Returns the negation of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"negate(5)"#,
            expected: r#"-5"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "next",
        description: "Resumes a generator coroutine and returns its next value and completion status.",
        params: &["stream"],
        param_types: &["dynamic"],
        returns: "dict",
        examples: &[BuiltinExample {
            code: r#"def g(): yield: 1; | let stream = g() | next(stream)"#,
            expected: r#"{"value": 1, "done": false}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "not",
        description: "Performs a logical NOT operation on a boolean value.",
        params: &["value"],
        param_types: &["bool"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"not(true)"#,
            expected: r#"false"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "now",
        description: "Returns the current timestamp.",
        params: &[],
        param_types: &[],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "open_file",
        description: "Opens the file at the given path for incremental reading and returns a file handle. Read from it with `read_line` or `read_bytes`. The file is closed by `close(handle)`, or automatically when the handle (or a coroutine holding it) is closed, finishes, or is dropped. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "file",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "open_http",
        description: "Opens an HTTPS request with the given method (a string or symbol, same as http()) and returns the response body as a streaming reader handle instead of buffering it, so it can be read incrementally with read_line/read_bytes rather than waiting for the whole response. body/headers behave the same as http(). The connection is closed by close(handle), or automatically when the handle (or a coroutine holding it) is closed, finishes, or is dropped. Requires the --allow-net CLI flag; otherwise returns a runtime error. Only https:// URLs are allowed.",
        params: &["method", "url", "body", "headers"],
        param_types: &["string", "string", "string", "dict"],
        returns: "http",
        examples: &[],
        capability: Some("http"),
    },
    BuiltinDoc {
        name: "or",
        description: "Performs a logical OR operation on two boolean values.",
        params: &["value1", "value2"],
        param_types: &["bool", "bool"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"or(true, false)"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "pack",
        description: "Packs a number into bytes using the given format. Supported formats: u8, i8, u16be/le, i16be/le, u32be/le, i32be/le, u64be/le, i64be/le, f32be/le, f64be/le.",
        params: &["format", "value"],
        param_types: &["string", "number"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "partial",
        description: "Creates a new function by partially applying the given arguments to the specified function.",
        params: &["function", "arg1", "arg2", "..."],
        param_types: &["function", "dynamic"],
        returns: "function",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "path_join",
        description: "Joins a base path with a component path and returns the resulting path string (e.g. path_join(\"/a/b\", \"c.txt\") → \"/a/b/c.txt\").",
        params: &["base", "component"],
        param_types: &["string", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"path_join("/a/b", "c.txt")"#,
            expected: r#"/a/b/c.txt"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "pow",
        description: "Raises the base to the power of the exponent.",
        params: &["base", "exponent"],
        param_types: &["number", "number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"pow(2, 10)"#,
            expected: r#"1024"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "print",
        description: "Prints a message to standard output and returns the current value.",
        params: &["message"],
        param_types: &["string"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "rand",
        description: "Generates a pseudo-random number in the range [0, 1). Not cryptographically secure. `seed` is optional; when given, the result is a deterministic function of it instead of OS entropy.",
        params: &["seed?"],
        param_types: &["number"],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "rand_int",
        description: "Generates a pseudo-random integer uniformly distributed in [min, max] (inclusive). Not cryptographically secure. `seed` is optional; when given, the result is a deterministic function of it instead of OS entropy.",
        params: &["min", "max", "seed?"],
        param_types: &["number", "number", "number"],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "random_string",
        description: "Generates a random string of `len` characters, each independently chosen (with replacement) from `charset`. Not cryptographically secure. `seed` is optional; when given, the result is a deterministic function of it instead of OS entropy.",
        params: &["len", "charset", "seed?"],
        param_types: &["number", "string", "number"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "range",
        description: "Creates an array from start to end with an optional step.",
        params: &["start", "end", "step"],
        param_types: &["number", "number", "number"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"range(0, 5, 1)"#,
            expected: r#"[0, 1, 2, 3, 4, 5]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "read_bytes",
        description: "Reads up to `size` bytes from a reader handle (fewer only at end of file), or returns `None` at end of file. `size` must be a positive integer. Errors if the handle is closed.",
        params: &["handle", "size"],
        param_types: &["dynamic", "number"],
        returns: "bytes",
        examples: &[],
        capability: Some("file-io or http"),
    },
    BuiltinDoc {
        name: "read_file",
        description: "Reads the contents of a file at the given path and returns it as a string. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "string",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "read_file_bytes",
        description: "Reads the contents of a file at the given path and returns it as raw bytes. Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["path"],
        param_types: &["string"],
        returns: "bytes",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "read_line",
        description: "Reads the next line from a reader handle without its `\\n`/`\\r\\n` terminator, or returns `None` at end of file. Errors if the handle is closed or the line is not valid UTF-8.",
        params: &["handle"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[],
        capability: Some("file-io or http"),
    },
    BuiltinDoc {
        name: "regex_escape",
        description: "Escapes regular expression metacharacters in the given string so it can be used literally in a regex pattern (e.g. with `regex_match`, `is_regex_match`, `capture`, `scan`, `gsub`, or `split`). This is for building patterns from dynamic input, not for escaping replacement strings.",
        params: &["string"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"regex_escape("a.b*c?")"#,
            expected: r#"a\.b\*c\?"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "regex_match",
        description: "Finds all matches of the given pattern in the string.",
        params: &["string", "pattern"],
        param_types: &["string", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"regex_match("abc123", "[0-9]+")"#,
            expected: r#"["123"]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "repeat",
        description: "Repeats the given string a specified number of times.",
        params: &["string", "count"],
        param_types: &["string", "number"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"repeat("ab", 3)"#,
            expected: r#"ababab"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "replace",
        description: "Replaces all occurrences of a substring or byte subsequence with another one.",
        params: &["from", "pattern", "to"],
        param_types: &["dynamic", "dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"replace("aXbXc", "X", "-")"#,
            expected: r#"a-b-c"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "reverse",
        description: "Reverses the given string or array.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"reverse("abc")"#,
            expected: r#"cba"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "rindex",
        description: "Finds the last occurrence of a substring or byte subsequence. Returns -1 if not found.",
        params: &["value", "needle"],
        param_types: &["dynamic", "dynamic"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"rindex("hello", "l")"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "round",
        description: "Rounds the given number to the nearest integer.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"round(3.5)"#,
            expected: r#"4"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "rtrim",
        description: "Trims whitespace from the right end of the given string or byte array.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"rtrim("  hi  ")"#,
            expected: r#"  hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "sample",
        description: "Returns n elements sampled from the array without replacement, in random order. Errors if n exceeds the array length. `seed` is optional; when given, the sample is a deterministic function of it instead of OS entropy.",
        params: &["array", "n", "seed?"],
        param_types: &["array", "number", "number"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "sanitize_html",
        description: "Sanitizes the given HTML string using an allowlist of safe tags and attributes, removing scripts and other XSS vectors.",
        params: &["html"],
        param_types: &["string"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "scan",
        description: "Finds all matches of a regular expression pattern in the string. For each match, returns the captured groups as an array if the pattern has capture groups, otherwise returns the whole match as a string.",
        params: &["string", "pattern"],
        param_types: &["string", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"scan("a1b2", "[0-9]")"#,
            expected: r#"["1", "2"]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "send",
        description: "Resumes a generator coroutine like `next`, but resumes its suspended `yield` expression to `value` instead of `None`.",
        params: &["stream", "value"],
        param_types: &["dynamic", "dynamic"],
        returns: "dict",
        examples: &[BuiltinExample {
            code: r#"def g(): let a = yield: 1 | yield: a; | let stream = g() | next(stream) | send(stream, 2)"#,
            expected: r#"{"value": 2, "done": false}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "set",
        description: "Sets a key-value pair in a dict. If the key exists, its value is updated. Returns the modified map.",
        params: &["obj", "key", "value"],
        param_types: &["dict", "dynamic", "dynamic"],
        returns: "dict",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "set_attr",
        description: "Sets the value of the specified attribute on a markdown node.",
        params: &["markdown", "attribute", "value"],
        param_types: &["markdown", "string", "dynamic"],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "set_check",
        description: "Creates a markdown list node with the given checked state.",
        params: &["list", "checked"],
        param_types: &["markdown", "bool"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"set_check(to_md_list("Item", 0), true)"#,
            expected: r#"- [x] Item"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "set_children",
        description: "Sets the children nodes of a markdown node. Nodes without children (e.g. text, code) are left unchanged.",
        params: &["markdown", "children"],
        param_types: &["markdown", "array"],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "set_code_block_lang",
        description: "Sets the language of a markdown code block node.",
        params: &["code_block", "language"],
        param_types: &["markdown", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"set_code_block_lang(to_code("x", "python"), "rust")"#,
            expected: r#"```rust
x
```"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "set_list_ordered",
        description: "Sets the ordered property of a markdown list node.",
        params: &["list", "ordered"],
        param_types: &["markdown", "bool"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"set_list_ordered(to_md_list("Item", 0), true)"#,
            expected: r#"1. Item"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "set_ref",
        description: "Sets the reference identifier for markdown nodes that support references (e.g., Definition, LinkRef, ImageRef, Footnote, FootnoteRef).",
        params: &["node", "reference_id"],
        param_types: &["markdown", "string"],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "sha256",
        description: "Computes the SHA-256 hash of a string or bytes and returns a lowercase hex string.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "sha512",
        description: "Computes the SHA-512 hash of a string or bytes and returns a lowercase hex string.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "shift_left",
        description: "Performs a left shift operation on the given value: for numbers, this is a bitwise left shift by the specified number of positions; for strings, this removes characters from the start; for Markdown headings, this increases the heading level accordingly.",
        params: &["value", "shift_amount"],
        param_types: &["dynamic", "number"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"shift_left(1, 2)"#,
            expected: r#"4"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "shift_right",
        description: "Performs a bitwise right shift on numbers, slices characters from the end of strings, and adjusts Markdown heading levels when applied to headings, using the given shift amount.",
        params: &["value", "shift_amount"],
        param_types: &["dynamic", "number"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"shift_right(8, 2)"#,
            expected: r#"2"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "shuffle",
        description: "Returns a new array containing the same elements as the input, in a uniformly random order. `seed` is optional; when given, the permutation is a deterministic function of it instead of OS entropy.",
        params: &["array", "seed?"],
        param_types: &["array", "number"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "sin",
        description: "Returns the sine of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"sin(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "sinh",
        description: "Returns the hyperbolic sine of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"sinh(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "slice",
        description: "Extracts a substring from the given string.",
        params: &["string", "start", "end"],
        param_types: &["string", "number", "number"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"slice("hello", 1, 3)"#,
            expected: r#"el"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "sort",
        description: "Sorts the elements of the given array.",
        params: &["array"],
        param_types: &["array"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"sort([3, 1, 2])"#,
            expected: r#"[1, 2, 3]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "split",
        description: "Splits the given string (as a regular expression) or byte array (literal separator) by the specified separator.",
        params: &["value", "separator"],
        param_types: &["dynamic", "dynamic"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"split("a,b,c", ",")"#,
            expected: r#"["a", "b", "c"]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "split_records",
        description: "Splits a string by a regular expression separator into `{text, index, start_byte, end_byte, terminator}` records, keeping each piece's byte range and the separator that followed it (`terminator` is None for the last piece). Errors if the separator matches an empty string.",
        params: &["value", "separator"],
        param_types: &["dynamic", "string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"split_records("a,b,c", ",")"#,
            expected: r#"[{"text": "a", "index": 0, "start_byte": 0, "end_byte": 1, "terminator": ","}, {"text": "b", "index": 1, "start_byte": 2, "end_byte": 3, "terminator": ","}, {"text": "c", "index": 2, "start_byte": 4, "end_byte": 5, "terminator": }]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "sqrt",
        description: "Returns the square root of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"sqrt(9)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "starts_with",
        description: "Checks if the given string or byte array starts with the specified prefix.",
        params: &["value", "prefix"],
        param_types: &["dynamic", "dynamic"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"starts_with("hello", "he")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "status",
        description: "Returns a generator coroutine's lifecycle state as a symbol: `:created`, `:suspended`, `:running`, `:completed`, or `:failed`.",
        params: &["stream"],
        param_types: &["dynamic"],
        returns: "symbol",
        examples: &[BuiltinExample {
            code: r#"def g(): yield: 1; | status(g())"#,
            expected: r#":created"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "stderr",
        description: "Prints a message to standard error and returns the current value.",
        params: &["message"],
        param_types: &["string"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "stem",
        description: "Returns the file name without the extension (e.g. \"file\" from \"/a/b/file.txt\").",
        params: &["path"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"stem("/a/b/file.txt")"#,
            expected: r#"file"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "strftime",
        description: "Formats a Unix timestamp (seconds) as a date string using the given strftime format (e.g. \"%Y-%m-%d\").",
        params: &["timestamp", "format"],
        param_types: &["number", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"strftime(0, "%Y-%m-%d")"#,
            expected: r#"1970-01-01"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "strip_tags",
        description: "Removes HTML tags from the given string, keeping the surrounding text content.",
        params: &["string"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"strip_tags("<b>hi</b>")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "strptime",
        description: "Parses a date string using the given strptime format (e.g. \"%Y-%m-%d\") and returns a Unix timestamp (seconds, UTC).",
        params: &["date_str", "format"],
        param_types: &["string", "string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"strptime("1970-01-01", "%Y-%m-%d")"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "sub",
        description: "Subtracts the second value from the first value.",
        params: &["value1", "value2"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"sub(5, 2)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "system",
        description: "Runs command as a child process, optionally passing an array of string args, and returns its captured stdout as a string. The command is never run through a shell, so shell metacharacters in args are never interpreted. A non-zero exit status is a runtime error that includes the process's stderr. Requires the --allow-run CLI flag; otherwise returns a runtime error.",
        params: &["command", "args"],
        param_types: &["string", "array"],
        returns: "string",
        examples: &[],
        capability: Some("process-io"),
    },
    BuiltinDoc {
        name: "tan",
        description: "Returns the tangent of the given number (in radians).",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"tan(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "tanh",
        description: "Returns the hyperbolic tangent of the given number.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"tanh(0)"#,
            expected: r#"0"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_array",
        description: "Converts the given value to an array.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"to_array(1)"#,
            expected: r#"[1]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_blockquote",
        description: "Creates a markdown blockquote node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_blockquote("Quote")"#,
            expected: r#"> Quote"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_boolean",
        description: "Converts the given value to a boolean. Booleans are returned unchanged, the strings \"true\" and \"false\" are converted to their boolean equivalent, and all other input results in an error.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "bool",
        examples: &[BuiltinExample {
            code: r#"to_boolean("true")"#,
            expected: r#"true"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_break",
        description: "Creates a markdown hard line break node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_break()"#,
            expected: "\\\n",
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_bytes",
        description: "Converts a string (UTF-8), array of numbers, or bytes to raw bytes.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_callout",
        description: "Creates a markdown callout node with the given value, kind, and title.",
        params: &["value", "kind", "title"],
        param_types: &["dynamic", "string", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_callout("Note text", "note", "")"#,
            expected: r#"> [!NOTE]
> Note text"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_code",
        description: "Creates a markdown code block with the given value and language.",
        params: &["value", "language"],
        param_types: &["dynamic", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_code("x = 1", "python")"#,
            expected: r#"```python
x = 1
```"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_code_inline",
        description: "Creates an inline markdown code node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_code_inline("x")"#,
            expected: r#"`x`"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_date",
        description: "Converts a timestamp to a date string with the given format.",
        params: &["timestamp", "format"],
        param_types: &["number", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"to_date(0, "%Y-%m-%d")"#,
            expected: r#"1970-01-01"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_definition",
        description: "Creates a markdown link reference definition node with the given url, identifier, and title.",
        params: &["url", "ident", "title"],
        param_types: &["string", "string", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_definition("https://example.com", "ex", "")"#,
            expected: r#"[ex]: https://example.com"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_delete",
        description: "Creates a markdown delete (strikethrough) node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_delete("Old")"#,
            expected: r#"~~Old~~"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_em",
        description: "Creates a markdown emphasis (italic) node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_em("Italic")"#,
            expected: r#"*Italic*"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_footnote",
        description: "Creates a markdown footnote definition node with the given value and identifier.",
        params: &["value", "ident"],
        param_types: &["dynamic", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_footnote("Footnote text", "1")"#,
            expected: r#"[^1]: Footnote text"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_footnote_ref",
        description: "Creates a markdown footnote reference node with the given identifier.",
        params: &["ident"],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_footnote_ref("1")"#,
            expected: r#"[^1]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_h",
        description: "Creates a markdown heading node with the given value and depth.",
        params: &["value", "depth"],
        param_types: &["dynamic", "number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 1)"#,
            expected: r#"# Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_hex",
        description: "Encodes raw bytes as a lowercase hex string.",
        params: &["bytes"],
        param_types: &["bytes"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"to_hex(from_hex("6869"))"#,
            expected: r#"6869"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_hr",
        description: "Creates a markdown horizontal rule node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_hr()"#,
            expected: r#"***"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_html",
        description: "Converts the given markdown string to HTML.",
        params: &["markdown"],
        param_types: &["string"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_image",
        description: "Creates a markdown image node with the given URL, alt text, and title.",
        params: &["url", "alt", "title"],
        param_types: &["string", "string", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_image("https://example.com/a.png", "Alt", "")"#,
            expected: r#"![Alt](https://example.com/a.png "")"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_link",
        description: "Creates a markdown link node  with the given  url and title.",
        params: &["url", "value", "title"],
        param_types: &["string", "dynamic", "string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_link("https://example.com", "Example", "")"#,
            expected: r#"[Example](https://example.com)"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_markdown",
        description: "Parses a markdown string and returns an array of markdown nodes.",
        params: &["markdown_string"],
        param_types: &["string"],
        returns: "array",
        examples: &[BuiltinExample {
            code: r##"to_markdown("# Hi")"##,
            expected: r#"[# Hi]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_markdown_string",
        description: "Converts the given value(s) to a markdown string representation.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_math",
        description: "Creates a markdown math block with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_math("x^2")"#,
            expected: r#"$$
x^2
$$"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_math_inline",
        description: "Creates an inline markdown math node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_math_inline("x^2")"#,
            expected: r#"$x^2$"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_fragment",
        description: "Creates a markdown fragment node that groups an array of markdown nodes into a single value.",
        params: &["values"],
        param_types: &["array"],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_html",
        description: "Creates a raw markdown HTML node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_html("<br>")"#,
            expected: r#"<br>"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_list",
        description: "Creates a markdown list node with the given value and indent level.",
        params: &["value", "indent"],
        param_types: &["dynamic", "number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_list("Item", 0)"#,
            expected: r#"- Item"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_name",
        description: "Returns the name of the given markdown node.",
        params: &["markdown"],
        param_types: &["markdown"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"to_md_name(to_h("t", 1))"#,
            expected: r#"h1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_table_align",
        description: "Creates a markdown table alignment row node from an array of alignments (\"left\", \"right\", \"center\", \"none\").",
        params: &["aligns"],
        param_types: &["array"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_table_align(["left", "right"])"#,
            expected: r#"|:---|---:|"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_table_cell",
        description: "Creates a markdown table cell node with the given value at the specified row and column.",
        params: &["value", "row", "column"],
        param_types: &["dynamic", "number", "number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_table_cell("A1", 0, 0)"#,
            expected: r#"A1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_table_row",
        description: "Creates a markdown table row node with the given values.",
        params: &["cells"],
        param_types: &["array"],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_md_text",
        description: "Creates a markdown text node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_text("hi")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_mdx",
        description: "Parses an MDX string and returns an array of MDX nodes.",
        params: &["mdx_string"],
        param_types: &["string"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "to_number",
        description: "Converts the given value to a number.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"to_number("42")"#,
            expected: r#"42"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_string",
        description: "Converts the given value to a string.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"to_string(1)"#,
            expected: r#"1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_strong",
        description: "Creates a markdown strong (bold) node with the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_strong("Bold")"#,
            expected: r#"**Bold**"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "to_text",
        description: "Converts the given markdown node to plain text.",
        params: &["markdown"],
        param_types: &["markdown"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"to_text(to_strong("hi"))"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "token_compress",
        description: "Reduces an array of Markdown nodes to fit within `budget` LLM tokens, preserving structure as much as possible: paragraphs are cut to their first sentence, then lists/tables/code blocks are collapsed to a summary, and only as a last resort is the remaining text hard-truncated. Uses a lightweight chars-per-token heuristic by default; built with the `tiktoken` Cargo feature, counts exactly via tiktoken-rs instead when `model` (e.g. \"gpt-5\") is given. `model` is optional; without it, the heuristic estimate is always used.",
        params: &["nodes", "budget", "model?"],
        param_types: &["array", "number", "string"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "token_count",
        description: "Estimates how many LLM tokens the given text would consume, for context-window budgeting. Uses a lightweight chars-per-token heuristic by default; built with the `tiktoken` Cargo feature, counts exactly via tiktoken-rs instead when `model` (e.g. \"gpt-5\") is given. `model` is optional; without it, the heuristic estimate is always used.",
        params: &["text", "model?"],
        param_types: &["string", "string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"token_count("Hello, world!")"#,
            expected: r#"4"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "trim",
        description: "Trims whitespace from both ends of the given string or byte array.",
        params: &["input"],
        param_types: &["dynamic"],
        returns: "dynamic",
        examples: &[BuiltinExample {
            code: r#"trim("  hi  ")"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "trunc",
        description: "Truncates the given number to an integer by removing the fractional part.",
        params: &["number"],
        param_types: &["number"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"trunc(3.9)"#,
            expected: r#"3"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "truncate",
        description: "Truncates the given string to the specified display width, appending the ellipsis string when truncated (CJK and other wide characters count as two columns).",
        params: &["string", "width", "ellipsis"],
        param_types: &["string", "number", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"truncate("hello world", 5, "...")"#,
            expected: r#"he..."#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "type",
        description: "Returns the type of the given value.",
        params: &["value"],
        param_types: &["dynamic"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"type(1)"#,
            expected: r#"number"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "unicode_normalize",
        description: "Normalizes the string to a Unicode normalization form: \"nfc\", \"nfd\", \"nfkc\", or \"nfkd\".",
        params: &["input", "form"],
        param_types: &["string", "string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"unicode_normalize("e\u{0301}", "nfc")"#,
            expected: "\u{00e9}",
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "unpack",
        description: "Unpacks a number from bytes using the given format. Supported formats: u8, i8, u16be/le, i16be/le, u32be/le, i32be/le, u64be/le, i64be/le, f32be/le, f64be/le.",
        params: &["format", "bytes"],
        param_types: &["string", "bytes"],
        returns: "number",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "upcase",
        description: "Converts the given string to uppercase.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"upcase("abc")"#,
            expected: r#"ABC"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "update",
        description: "Update the value with specified value.",
        params: &["target_value", "source_value"],
        param_types: &["dynamic", "dynamic"],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "url_decode",
        description: "URL-decodes the given string.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"url_decode("a%20b")"#,
            expected: r#"a b"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "url_encode",
        description: "URL-encodes the given string.",
        params: &["input"],
        param_types: &["string"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"url_encode("a b")"#,
            expected: r#"a%20b"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "utf8",
        description: "Decodes bytes as a UTF-8 string, returning an error if the bytes are not valid UTF-8.",
        params: &["bytes"],
        param_types: &["bytes"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"utf8(to_bytes("hi"))"#,
            expected: r#"hi"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "utf8bytelen",
        description: "Returns the number of bytes of the given string when encoded as UTF-8.",
        params: &["string"],
        param_types: &["string"],
        returns: "number",
        examples: &[BuiltinExample {
            code: r#"utf8bytelen("héllo")"#,
            expected: r#"6"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "uuid",
        description: "Generates a random (version 4, RFC 4122) UUID string.",
        params: &[],
        param_types: &[],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "uuid_v4",
        description: "Generates a random (version 4, RFC 4122) UUID string. Alias of `uuid`.",
        params: &[],
        param_types: &[],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "uuid_v7",
        description: "Generates a time-ordered (version 7, RFC 9562) UUID string: a millisecond Unix timestamp followed by random bits, so values sort by creation time. The timestamp is plaintext, so prefer uuid/uuid_v4 for unguessable IDs.",
        params: &[],
        param_types: &[],
        returns: "string",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "values",
        description: "Returns an array of values from the dict.",
        params: &["dict"],
        param_types: &["dict"],
        returns: "array",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "walk_files",
        description: "Recursively enumerates filesystem entries under `root` whose root-relative path (using `/` as the separator regardless of platform) matches the glob `pattern` (default `\"**\"`, i.e. every file), returning a stable-sorted array of those relative path strings. Unlike `collection`, this reads neither file contents nor Markdown. An optional third argument is a dict of options: `respect_gitignore` (default `false`, same semantics as `collection`) and `follow_symlinks` (default `false`; a symlinked file is always included if it matches, only directory traversal is affected). Requires the --allow-read CLI flag; otherwise returns a runtime error.",
        params: &["root", "pattern?", "options?"],
        param_types: &["string", "string", "dict"],
        returns: "array",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "word_wrap",
        description: "Wraps the given string into lines no wider than the specified display width, breaking on word boundaries (CJK and other wide characters count as two columns).",
        params: &["string", "width"],
        param_types: &["string", "number"],
        returns: "string",
        examples: &[BuiltinExample {
            code: r#"word_wrap("hello world", 5)"#,
            expected: r#"hello
world"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: "write_file",
        description: "Writes content (string or bytes) to the file at the given path, creating or truncating it. Requires the --allow-write CLI flag; otherwise returns a runtime error.",
        params: &["path", "content"],
        param_types: &["string", "dynamic"],
        returns: "dynamic",
        examples: &[],
        capability: Some("file-io"),
    },
    BuiltinDoc {
        name: "xor",
        description: "Computes the bitwise XOR of two byte arrays of equal length.",
        params: &["bytes1", "bytes2"],
        param_types: &["bytes", "bytes"],
        returns: "bytes",
        examples: &[],
        capability: None,
    },
]);
