use super::{BuiltinDoc, DocTable};

/// Documentation for internal helpers used by `builtin.mq`.
pub static INTERNAL_FUNCTION_DOC: DocTable = DocTable::new(&[
    BuiltinDoc {
        name: "_cbor_parse",
        description: "Parses a base64-encoded CBOR string or raw bytes into a data structure.",
        params: &["input"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_cbor_stringify",
        description: "Serializes a value to CBOR bytes.",
        params: &["value"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_csv_parse",
        description: "Parses a CSV string into an array of arrays, using the specified delimiter and header options.",
        params: &["csv_string", "delimiter", "has_header"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_diff",
        description: "Internal function to compute the difference between two values, returning an array of changes.",
        params: &["value1", "value2"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_get_markdown_position",
        description: "Internal function to get the position information of a markdown node, returning row and column data if available.",
        params: &["markdown_node"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_gron_parse",
        description: "Parses gron-style `path = value;` assignment statements into a data structure.",
        params: &["gron_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_html_parse",
        description: "Parses an HTML string and returns the corresponding data structure.",
        params: &["html_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: Some("css-selector"),
    },
    BuiltinDoc {
        name: "_jaro_distance",
        description: "Calculates the Jaro distance between two strings (0.0 to 1.0, where 1.0 is an exact match).",
        params: &["s1", "s2"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_jaro_winkler_distance",
        description: "Calculates the Jaro-Winkler distance between two strings, boosting scores for matching prefixes.",
        params: &["s1", "s2"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_json_parse",
        description: "Parses a JSON string into a data structure.",
        params: &["json_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_levenshtein_distance",
        description: "Calculates the Levenshtein edit distance between two strings.",
        params: &["s1", "s2"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_regex_replace_matches",
        description: "Internal implementation of regex_replace that splits `text` on every match of `pattern`, returning a dict with `segments` (the text between matches) and `matches` (per-match `match`/`captures`/`start`/`end` info).",
        params: &["text", "pattern"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_sort_by_impl",
        description: "Internal implementation of sort_by functionality that sorts arrays of arrays using the first element as the key.",
        params: &[],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_toml_parse",
        description: "Parses a TOML string into a data structure.",
        params: &["toml_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_toon_parse",
        description: "Parses a TOON string into a data structure.",
        params: &["toon_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_toon_stringify",
        description: "Converts a data structure into a TOON string.",
        params: &["data"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_xml_parse",
        description: "Parses an XML string and returns the corresponding data structure.",
        params: &["xml_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "_yaml_parse",
        description: "Parses a YAML string into a data structure.",
        params: &["yaml_string"],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: "is_debug_mode",
        description: "Checks if the runtime is currently in debug mode, returning true if a debugger is attached.",
        params: &[],
        param_types: &[],
        returns: "dynamic",
        examples: &[],
        capability: None,
    },
]);
