use super::{BuiltinDoc, BuiltinExample, DocTable};

/// Documentation for every native selector.
pub static BUILTIN_SELECTOR_DOC: DocTable = DocTable::new(&[
    BuiltinDoc {
        name: "..",
        description: "Recursively selects every descendant node (depth-first), not the node itself. Combine with a following selector for a descendant chain, e.g. `.blockquote .code` (sugar for `.blockquote | .. | .code`).",
        params: &[],
        param_types: &[],
        returns: "array",
        examples: &[BuiltinExample {
            code: r#"to_markdown("> ## Nested")[0] | .."#,
            expected: "[Nested, ## Nested]",
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".<>",
        description: "Selects an HTML node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: ".[]",
        description: "Selects a list item node, optionally filtered by item index (e.g. `.[](0)`). To filter by checked state, use `.task`/`.todo`/`.done` instead.",
        params: &["index", "..."],
        param_types: &["number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_list("Item", 0) | .[]"#,
            expected: r#"- Item"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".[][]",
        description: "Selects a table cell node with the specified row and column.",
        params: &["row", "column"],
        param_types: &["number", "number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_table_cell("A1", 0, 0) | .[][]"#,
            expected: r#"A1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".blockquote",
        description: "Selects a blockquote node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_blockquote("Quote") | .blockquote"#,
            expected: r#"> Quote"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".break",
        description: "Selects a break node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("Line1  \nLine2")[1] | .break"#,
            expected: "\\\n",
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".callout",
        description: "Selects an Obsidian-style callout node, optionally filtered by kind (e.g. `.callout(\"note\")`).",
        params: &["kind", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("> [!NOTE]\n> body")[0] | .callout"#,
            expected: r#"> [!NOTE]
> body"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".code",
        description: "Selects a code block node with the specified language.",
        params: &["lang", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_code("x = 1", "python") | .code"#,
            expected: r#"```python
x = 1
```"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".code_inline",
        description: "Selects an inline code node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_code_inline("x") | .code_inline"#,
            expected: r#"`x`"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".definition",
        description: "Selects a definition node, optionally filtered by identifier.",
        params: &["ident", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("[ref]: https://example.com")[0] | .definition"#,
            expected: r#"[ref]: https://example.com"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".delete",
        description: "Selects a delete (strikethrough) node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_delete("Old") | .delete"#,
            expected: r#"~~Old~~"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".done",
        description: "Selects a done item in the task list node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("- [ ] Todo\n- [x] Done")[1] | .done"#,
            expected: r#"- [x] Done"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".embed",
        description: "Selects an Obsidian-style embed node, optionally filtered by target.",
        params: &["target", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("![[image.png]]")[0] | .embed"#,
            expected: r#"![[image.png]]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".emphasis",
        description: "Selects an emphasis (italic) node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_em("Italic") | .emphasis"#,
            expected: r#"*Italic*"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".footnote",
        description: "Selects a footnote node, optionally filtered by identifier.",
        params: &["ident", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("Text[^1]\n\n[^1]: Note")[2] | .footnote"#,
            expected: r#"[^1]: Note"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".footnote_ref",
        description: "Selects a footnote reference node, optionally filtered by identifier.",
        params: &["ident", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("Text[^1]\n\n[^1]: Note")[1] | .footnote_ref"#,
            expected: r#"[^1]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h",
        description: "Selects a heading node with the specified depth.",
        params: &["depth", "..."],
        param_types: &["number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 3) | .h"#,
            expected: r#"### Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h1",
        description: "Selects a heading node with the 1 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 1) | .h1"#,
            expected: r#"# Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h2",
        description: "Selects a heading node with the 2 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 2) | .h2"#,
            expected: r#"## Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h3",
        description: "Selects a heading node with the 3 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 3) | .h3"#,
            expected: r#"### Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h4",
        description: "Selects a heading node with the 4 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 4) | .h4"#,
            expected: r#"#### Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h5",
        description: "Selects a heading node with the 5 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 5) | .h5"#,
            expected: r#"##### Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".h6",
        description: "Selects a heading node with the 6 depth.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 6) | .h6"#,
            expected: r#"###### Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".heading",
        description: "Selects a heading node with the specified depth.",
        params: &["depth", "..."],
        param_types: &["number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_h("Title", 2) | .heading"#,
            expected: r#"## Title"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".horizontal_rule",
        description: "Selects a horizontal rule node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_hr() | .horizontal_rule"#,
            expected: r#"***"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".html",
        description: "Selects an HTML node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("<div>hi</div>")[0] | .html"#,
            expected: r#"<div>hi</div>"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".image",
        description: "Selects an image node, optionally filtered by URL (e.g. `.image(\"a.png\")`).",
        params: &["url", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_image("https://example.com/a.png", "Alt", "") | .image"#,
            expected: r#"![Alt](https://example.com/a.png "")"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".image_ref",
        description: "Selects an image reference node, optionally filtered by identifier.",
        params: &["ident", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("![alt][ref]\n\n[ref]: https://example.com/a.png")[0] | .image_ref"#,
            expected: r#"![alt][ref]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".inline_math",
        description: "Selects an inline math node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_math_inline("x^2") | .inline_math"#,
            expected: r#"$x^2$"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".link",
        description: "Selects a link node, optionally filtered by URL (e.g. `.link(\"https://example.com\")`).",
        params: &["url", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_link("https://example.com", "Example", "") | .link"#,
            expected: r#"[Example](https://example.com)"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".link_ref",
        description: "Selects a link reference node, optionally filtered by identifier.",
        params: &["ident", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("[text][ref]\n\n[ref]: https://example.com")[0] | .link_ref"#,
            expected: r#"[text][ref]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".list",
        description: "Selects a list item node, optionally filtered by item index (e.g. `.list(0)`). To filter by checked state, use `.task`/`.todo`/`.done` instead.",
        params: &["index", "..."],
        param_types: &["number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_list("Item", 0) | .list"#,
            expected: r#"- Item"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".math",
        description: "Selects a math node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_math("x^2") | .math"#,
            expected: r#"$$
x^2
$$"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".math_inline",
        description: "Selects a math inline node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_math_inline("x^2") | .math_inline"#,
            expected: r#"$x^2$"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".mdx_flow_expression",
        description: "Selects an MDX flow expression node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_mdx("{1 + 1}")[0] | .mdx_flow_expression"#,
            expected: r#"{1 + 1}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".mdx_js_esm",
        description: "Selects an MDX JS ESM node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[],
        capability: None,
    },
    BuiltinDoc {
        name: ".mdx_jsx_flow_element",
        description: "Selects an MDX JSX flow element node, optionally filtered by tag name.",
        params: &["name", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_mdx("<Foo />")[0] | .mdx_jsx_flow_element"#,
            expected: r#"<Foo />"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".mdx_jsx_text_element",
        description: "Selects an MDX JSX text element node, optionally filtered by tag name.",
        params: &["name", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_mdx("Hello <b>world</b>.")[1] | .mdx_jsx_text_element"#,
            expected: r#"<b>world</b>"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".mdx_text_expression",
        description: "Selects an MDX text expression node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_mdx("Value is {1 + 1}.")[1] | .mdx_text_expression"#,
            expected: r#"{1 + 1}"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".strong",
        description: "Selects a strong (bold) node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_strong("Bold") | .strong"#,
            expected: r#"**Bold**"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".table",
        description: "Selects a table cell node with the specified row and column.",
        params: &["row", "column"],
        param_types: &["number", "number"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_table_cell("A1", 0, 0) | .table"#,
            expected: r#"A1"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".table_align",
        description: "Selects a table align node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_table_align(["left", "right"]) | .table_align"#,
            expected: r#"|:---|---:|"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".task",
        description: "Selects a task list node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("- [ ] Todo\n- [x] Done")[0] | .task"#,
            expected: r#"- [ ] Todo"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".text",
        description: "Selects a text node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_md_text("Hello") | .text"#,
            expected: r#"Hello"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".todo",
        description: "Selects a todo item in the task list node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("- [ ] Todo\n- [x] Done")[0] | .todo"#,
            expected: r#"- [ ] Todo"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".toml",
        description: "Selects a TOML node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("+++\nkey = 1\n+++\n\nBody")[0] | .toml"#,
            expected: r#"+++
key = 1
+++"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".wikilink",
        description: "Selects an Obsidian-style wikilink node, optionally filtered by target.",
        params: &["target", "..."],
        param_types: &["string"],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("[[target]]")[0] | .wikilink"#,
            expected: r#"[[target]]"#,
        }],
        capability: None,
    },
    BuiltinDoc {
        name: ".yaml",
        description: "Selects a YAML node.",
        params: &[],
        param_types: &[],
        returns: "markdown",
        examples: &[BuiltinExample {
            code: r#"to_markdown("---\nkey: 1\n---\n\nBody")[0] | .yaml"#,
            expected: r#"---
key: 1
---"#,
        }],
        capability: None,
    },
]);
