[build]
# Enable Linker-Plugin LTO for all builds (including release)
# This can significantly reduce binary size.
rustflags = ["-C", "linker-plugin-lto=true"]

# Use LLD as the linker for common target platforms.
# LLD is generally faster and can produce smaller binaries.

[target.x86_64-unknown-linux-gnu]
linker = "lld"

[target.x86_64-apple-darwin]
linker = "lld"

[target.x86_64-pc-windows-msvc]
linker = "lld"
