[package]
authors.workspace = true
categories = ["command-line-utilities", "text-processing"]
description = "Test runner for mq"
edition.workspace = true
homepage = "https://mqlang.org/"
keywords = ["markdown", "jq", "query", "test"]
license.workspace = true
name = "mq-test"
repository.workspace = true
version.workspace = true

[dependencies]
clap = {workspace = true, features = ["derive"]}
glob = {workspace = true}
miette = {workspace = true, features = ["fancy"]}
mq-lang = {workspace = true, features = ["cst", "css-selector", "debugger", "file-io", "http", "mock-io"]}
rayon = {workspace = true}
rustc-hash = {workspace = true}
serde_json = {workspace = true}
similar = {workspace = true}

[dev-dependencies]
rstest = {workspace = true}

[[bin]]
name = "mq-test"
path = "src/main.rs"

[package.metadata.binstall]
pkg-fmt = "bin"
pkg-url = "{ repo }/releases/download/v{ version }/{ bin }-{ target }{ binary-ext }"
disabled-strategies = ["quick-install"]
