name: benchmarks

on:
  push:
    branches: ["main"]
    paths:
      - 'crates/mq-lang/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'crates/mq-lang/**'

concurrency:
  group: "benchmarks"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      - name: Install codspeed
        run: cargo install cargo-codspeed --locked
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Run benchmarks
        uses: CodSpeedHQ/action@63f3e98b61959fe67f146a3ff022e4136fe9bb9c # v4.17.6
        with:
          run: just bench
          mode: simulation
          token: ${{ secrets.CODSPEED_TOKEN }}
