name: benchmarks

on:
  push:
    branches: ["main"]
    paths:
      - 'crates/mq-lang/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'crates/mq-lang/**'

concurrency:
  group: "benchmarks"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      - name: Install codspeed
        run: cargo install cargo-codspeed --locked
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Run benchmarks
        uses: CodSpeedHQ/action@db35df748deb45fdef0960669f57d627c1956c30 # v4.13.1
        with:
          run: just bench
          mode: simulation
          token: ${{ secrets.CODSPEED_TOKEN }}
