name: Publish npm package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: extractions/setup-just@v2
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        working-directory: packages/mq-web
        run: npm ci
      - name: Build
        run: just build-web
      - name: Publish to npm
        working-directory: packages/mq-web
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
