name: Deploy docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "packages/mq-playground/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          package_json_file: packages/mq-playground/package.json
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .tool-versions
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      - name: Install tools
        uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: wasm-pack,mdbook
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Build
        run: just build-wasm
      - name: Build mdbook
        run: mdbook build -d ../book
        working-directory: ./docs/books
      - name: Install playground dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./packages/mq-playground
      - name: Build playground
        run: pnpm run build
        working-directory: ./packages/mq-playground
      - name: Copy install script
        run: |
          cp ./scripts/install.sh ./docs
          cp ./scripts/install_lsp.sh ./docs
          cp ./scripts/install_crawler.sh ./docs
      - name: Replace env vars
        env:
          API_URL: ${{ secrets.API_URL }}
        run: ./scripts/replace-env.sh
      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
