name: Deploy docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "packages/mq-playground/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
        with:
          package_json_file: packages/mq-playground/package.json
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .tool-versions
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      - name: Install tools
        uses: taiki-e/install-action@5939f3337e40968c39aa70f5ecb1417a92fb25a0 # v2.75.15
        with:
          tool: wasm-pack,mdbook
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Build
        run: just build-wasm
      - name: Build mdbook
        run: mdbook build -d ../book
        working-directory: ./docs/books
      - name: Install playground dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./packages/mq-playground
      - name: Build playground
        run: pnpm run build
        working-directory: ./packages/mq-playground
      - name: Copy install script
        run: |
          cp ./scripts/install.sh ./docs
          cp ./scripts/install_lsp.sh ./docs
          cp ./scripts/install_crawler.sh ./docs
      - name: Replace env vars
        env:
          API_URL: ${{ secrets.API_URL }}
        run: ./scripts/replace-env.sh
      - name: Deploy
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
