name: Unused Dependencies

on:
  pull_request:
    branches: ["main"]

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Machete
        uses: bnjbvr/cargo-machete@c78956ec6ebce8ecde709a045eb4d7fbf4d0860b # main
