name: Unused Dependencies

on:
  pull_request:
    branches: ["main"]

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Machete
        uses: bnjbvr/cargo-machete@d40d1e3265e4161d599ebb902eb9892faf769f6e # main
